set nocompatible
autocmd! bufwritepost .vimrc source %
set t_Co=256
color wombat256mod
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'Chiel92/vim-autoformat'
Plugin 'mattn/emmet-vim'

filetype plugin indent on

syntax on
set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab
set autoindent

set foldmethod=syntax

set nolist
set nowrap
