set nocompatible
autocmd! bufwritepost .vimrc source %
set t_Co=256
color wombat256mod

call plug#begin('~/.vim/plugged')
Plug 'Raimondi/delimitMate'
Plug 'Valloric/YouCompleteMe'
Plug 'Chiel92/vim-autoformat'
Plug 'mattn/emmet-vim'
Plug 'ctrlpvim/ctrlp.vim'
call plug#end()

filetype plugin indent on

syntax on
set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab
set autoindent
set foldmethod=indent
set nolist
set nowrap
