autocmd! bufwritepost .vimrc source %
set t_Co=256
color wombat256mod

filetype off
filetype plugin indent on

syntax on
set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab
set autoindent

set foldmethod=syntax

set list
