set nocompatible
autocmd! bufwritepost .vimrc source %

set t_Co=256
set background=dark
color wombat256mod

call plug#begin('~/.vim/plugged')
Plug 'Raimondi/delimitMate'
Plug 'Valloric/YouCompleteMe', { 'on': [] }
Plug 'Chiel92/vim-autoformat'  " help autoformat
Plug 'mattn/emmet-vim'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/nerdcommenter'  " help nerdcommenter
Plug 'nathanaelkane/vim-indent-guides'  " help indent-guides
Plug 'itchyny/lightline.vim'
Plug 'tpope/vim-fugitive'  " git wrapper, needed for lightline branch
" Plug 'easymotion/vim-easymotion'
call plug#end()


" lightline
set laststatus=2  " fix for lightline only show on :vsp
set noshowmode  " disable vim's default statusline
let g:lightline = {
  \ 'colorscheme': 'wombat',
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ],
  \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ]
  \ },
  \ 'component': {
  \   'readonly': '%{&filetype=="help"?"":&readonly?"RO":""}',
  \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"}',
  \   'fugitive': '%{exists("*fugitive#head")?fugitive#head():""}'
  \ },
  \ 'component_visible_condition': {
  \   'readonly': '(&filetype!="help"&& &readonly)',
  \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))',
  \   'fugitive': '(exists("*fugitive#head") && ""!=fugitive#head())'
  \ },
  \
  \
  \ }
"  \ 'separator': { 'left': '|', 'right': '|' },
"  \ 'subseparator': { 'left': '|', 'right': '|' }

set number
set tabstop=2
set softtabstop=2
set shiftwidth=2
set shiftround
set expandtab
set autoindent
set foldmethod=indent
set nolist
set nowrap

filetype plugin indent on
syntax on

" set correct fyletype for .twig
au BufNewFile,BufRead *.twig set filetype=html
